function f(x: Int, s: String) -> Float {
    return 0.4
}

f(10, 'foo')

try {
    __eval__('f(10, 20)')
    print('FAIL')
} catch Err(msg) :: 'constraint on s violated in call to f: s = 20' in msg {
    print('PASS')
}
